// Free photos of drum machines (Wikimedia Commons, chosen and checked by hand), shown in the sound browser.
// Credits: public/sounds/photos/CREDITS.md
export const PHOTOS = {
  RolandTR808: { file: 'sounds/photos/roland-tr-808.jpg', credit: "Brandon Daniel, derivative work by Clusternote \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Roland_TR-808_(large).jpg" },
  RolandTR909: { file: 'sounds/photos/roland-tr-909.png', credit: "Brandon Daniel, derivative work by Clusternote \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Roland_TR-909_(large).png" },
  LinnDrum: { file: 'sounds/photos/linndrum.jpg', credit: "Forat Electronics (Bruce Forat) \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:LinnDrum_digital_drum_machine_front_panel_.jpg" },
  RolandTR707: { file: 'sounds/photos/roland-tr-707.jpg', credit: "Speculos \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Roland_TR-707.jpg" },
  AkaiMPC60: { file: 'sounds/photos/akai-mpc60.jpg', credit: "Kimi95 (Italian Wikipedia) \u00b7 CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Akai_MPC60.jpg" },
  OberheimDMX: { file: 'sounds/photos/oberheim-dmx.jpg', credit: "Alison \u00b7 CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Oberheim_DMX_with_factory_MIDI.jpg" },
  RolandTR606: { file: "sounds/photos/roland-t-r606.jpg", credit: "Midas Wouters \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Roland_TR-606.jpg" },
  RolandTR505: { file: "sounds/photos/roland-t-r505.jpg", credit: "EternityofNight \u00b7 CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Roland_TR-505_4578.jpg" },
  RolandR8: { file: "sounds/photos/roland-r8.jpg", credit: "Candyman777 \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Roland_R-8_human_rhythm_composer.jpg" },
  RolandMC202: { file: "sounds/photos/roland-m-c202.jpg", credit: "1904.CC \u00b7 CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:Roland_MC-202_Synthesizer_at_SMEM_Playroom.jpg" },
  RolandMC303: { file: "sounds/photos/roland-m-c303.jpg", credit: "Nina Richards \u00b7 Public domain", page: "https://commons.wikimedia.org/wiki/File:MC-303.jpg" },
  RolandJD990: { file: "sounds/photos/roland-j-d990.jpg", credit: "Matt Perry \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Roland_JD-990_front.png" },
  RolandMT32: { file: "sounds/photos/roland-m-t32.jpg", credit: "Cloudschatze \u00b7 Public domain", page: "https://commons.wikimedia.org/wiki/File:MT_32.jpg" },
  RolandS50: { file: "sounds/photos/roland-s50.jpg", credit: "Gansweith \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Roland_S-50.jpg" },
  RolandSystem100: { file: "sounds/photos/roland-system100.jpg", credit: "Notreshuggie \u00b7 CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Roland_System_100_in_use.jpg" },
  RolandCompurhythm8000: { file: "sounds/photos/roland-compurhythm8000.jpg", credit: "Blair Rideout \u00b7 CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Roland_CR-8000_CompuRhythm.jpg" },
  EmuSP12: { file: "sounds/photos/emu-s-p12.jpg", credit: "Clusternote \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:E-mu_SP-12.png" },
  EmuDrumulator: { file: "sounds/photos/emu-drumulator.jpg", credit: "Andreas Gortan \u00b7 CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Drumulator_Vorderseite.png" },
  LinnLM1: { file: "sounds/photos/linn-l-m1.jpg", credit: "Ekwatts \u00b7 Public domain", page: "https://commons.wikimedia.org/wiki/File:Linn_LM-1_Drum_Computer.jpg" },
  Linn9000: { file: "sounds/photos/linn9000.jpg", credit: "Forat Electronics (Bruce Forat) \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Linn_9000_view_top_300dpi_2550_1635.jpg" },
  LinnLM2: { file: "sounds/photos/linn-l-m2.jpg", credit: "Forat Electronics (Bruce Forat) \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:LinnDrum_digital_drum_machine_front_panel_.jpg" },
  KorgKR55: { file: "sounds/photos/korg-k-r55.jpg", credit: "anders pearson \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Korg_Rhythm_55_(KR-55).jpg" },
  KorgM1: { file: "sounds/photos/korg-m1.jpg", credit: "Deepsonic from Switzerland \u00b7 CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Korg_M1_(2017-02-10_22.06.29_by_deepsonic)_(minor_filter).jpg" },
  KorgPoly800: { file: "sounds/photos/korg-poly800.jpg", credit: "Fataltourist \u00b7 Public domain", page: "https://commons.wikimedia.org/wiki/File:Korg_poly800.jpg" },
  YamahaRY30: { file: "sounds/photos/yamaha-r-y30.jpg", credit: "Solaria \u00b7 Public domain", page: "https://commons.wikimedia.org/wiki/File:YAMAHA_RY30.JPG" },
  CasioRZ1: { file: "sounds/photos/casio-r-z1.jpg", credit: "Brandon Daniel (derivative work) \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Casio_RZ-1_Digital_Sampling_Rhythm_Composer_(lowreso).jpg" },
  CasioSK1: { file: "sounds/photos/casio-s-k1.jpg", credit: "Vlad Spears (derivative work) \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Casio_SK-1.jpg" },
  CasioVL1: { file: "sounds/photos/casio-v-l1.jpg", credit: "Dontpanic \u00b7 CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Casio_vl_tone.jpg" },
  AlesisHR16: { file: "sounds/photos/alesis-h-r16.jpg", credit: "driftpattern \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Alesis_HR-16_modified.jpg" },
  AlesisSR16: { file: "sounds/photos/alesis-s-r16.jpg", credit: "David McMahon \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Alesis_SR-16,_Devi_Ever_OK.jpg" },
  AkaiLinn: { file: "sounds/photos/akai-linn.jpg", credit: "Kimi95 (Italian Wikipedia) \u00b7 CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Akai_MPC60.jpg" },
  MPC1000: { file: "sounds/photos/m-p-c1000.jpg", credit: "paulkhor \u00b7 CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Akai_MPC1000_black.jpg" },
  SequentialCircuitsDrumtracks: { file: "sounds/photos/sequential-circuits-drumtracks.jpg", credit: "Gerald Moore \u00b7 CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:SCI_model_400_drumtraks_-_front_mid.jpg" },
  SimmonsSDS5: { file: "sounds/photos/simmons-s-d-s5.jpg", credit: "Ben Franske (BenFranske) \u00b7 CC BY-SA 2.5", page: "https://commons.wikimedia.org/wiki/File:Simmons_SDS5_Electric_Drum.jpg" },
  MoogConcertMateMG1: { file: "sounds/photos/moog-concert-mate-m-g1.jpg", credit: "glacial23 (derivative work) \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Realistic_Concertmate_MG-1.jpg" },
  DoepferMS404: { file: "sounds/photos/doepfer-m-s404.jpg", credit: "deepsonic \u00b7 CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Doepfer_MS-404_(50952632408).jpg" },
  RhythmAce: { file: "sounds/photos/rhythm-ace.jpg", credit: "Alison Cassidy \u00b7 CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Multivox_Rhythm_Ace_FR-3S.jpg" },
};
