// Song v2 → Strudel code. One block per track; inside it, one layer group per clip and section.
// Each clip is generated by the per-instrument code generator (sceneLayers with `only`).
import { sceneLayers, sectionLane, uniqueNames, sectionInfo, songHeader, rle, ORBIT_OF } from '../music.js';
import { t } from '../i18n.js';
import { normalizeSong, clipState } from './format.js';
import { rackCode } from './rack.js';

const fadeIn = (secs, i) => i > 0 ? Math.min(secs[i].fade || 0, secs[i].bars) : 0;

export function compileSong(input) {
  const song = normalizeSong(input);
  const secs = song.sections, total = song.total;
  if (!secs.length) throw new Error('a song needs at least one section');
  const v1secs = secs.map(s => ({ bars: s.bars, fade: s.fade, bpm: s.bpm, bpmEnd: s.bpmEnd, meter: s.meter, key: s.key, prog: s.chords }));
  const names = uniqueNames(secs.map(s => s.name));
  const L = songHeader(song.title, v1secs[0], names, v1secs);
  // lanes: one per section (1 plays, 0 silent, values in between fade), as in v1
  const lanes = secs.map((_, i) => sectionLane(v1secs, i));
  L.push('', `// ${t('cSections')}`);
  secs.forEach((s, i) => L.push(`const section${i + 1} = "${rle(lanes[i].map(String))}"  // ${names[i]} · ${sectionInfo({ ...v1secs[i] }, fadeIn(v1secs, i))}`));

  // one bus per track: the first track of a type keeps the v1 orbit, the others get new ones
  const used = new Set();
  let clipLanes = 0, extra = 8;
  // muto e solo: le tracce silenziate non entrano nel codice
  const solo = song.tracks.some(tr => tr.solo);
  for (const tr of song.tracks) {
    // the bus is chosen before skipping muted tracks, so a track that comes in later (live build) does not move the others
    const orbit = !used.has(tr.type) && ORBIT_OF[tr.type] ? ORBIT_OF[tr.type] : ++extra;
    used.add(tr.type);
    // voice tracks speak the live build comments: their code comes from the build (build.js), not from clips
    if (tr.mute || (solo && !tr.solo) || tr.type === 'voice') continue;
    L.push('', `// ========== ${[...new Set([tr.name || tr.id, tr.type])].join(' · ')} ==========`);
    const rack = rackCode(tr.rack, tr.type);
    let described = null;
    for (const clip of tr.clips) {
      const end = clip.start + clip.bars;
      // a clip spanning several sections is compiled piece by piece: each piece follows its section's harmony
      secs.forEach((sec, i) => {
        const a = Math.max(clip.start, sec.start), b = Math.min(end, sec.start + sec.bars);
        if (a >= b) return;
        const whole = a === sec.start && b === sec.start + sec.bars;
        let gate = `section${i + 1}`;
        if (!whole) {
          // part of a section: plays in [a, b), fades in only from a section start, fades out into a fading section
          const v = Array(total).fill(0);
          for (let k = a; k < b; k++) v[k] = 1;
          if (a === sec.start) for (let k = 0; k < fadeIn(v1secs, i); k++) v[a + k] = lanes[i][a + k];
          if (b === sec.start + sec.bars) for (let k = b; k < total && lanes[i][k] > 0; k++) v[k] = lanes[i][k];
          gate = `clip${++clipLanes}`;
          L.push(`const ${gate} = "${rle(v.map(String))}"`);
        }
        L.push(`// ${names[i]} · ${t('cBars', { from: a + 1, to: b })} · ${t('cPattern', { p: clip.pattern })}`);
        const opts = { start: a, bars: b - a, gate, crash: sec.crash && a === sec.start, breath: sec.breath && b === sec.start + sec.bars, fill: sec.fill && b === sec.start + sec.bars, only: tr.type, orbit, rack };
        if (tr.type === 'code') L.push(...codeLayer(tr, clip, gate, orbit, rack));
        else {
          // the instrument comment ("// Bass · Rolling") is repeated per clip only when it changes
          const lines = sceneLayers(clipState(sec, tr, clip), opts).filter(l => l !== '');
          const desc = lines[0] && lines[0].startsWith('//') ? lines.shift() : null;
          if (desc && desc !== described) { L.push(desc); described = desc; }
          L.push(...lines);
        }
      });
    }
  }
  return L.join('\n');
}

// code track: the pattern is plain Strudel; the app adds the lane, the bus and the visual
function codeLayer(tr, clip, gate, orbit, rack = '') {
  const pat = (tr.patterns || {})[clip.pattern] || {};
  const code = String(pat.code || 'silence').trim().replace(/;\s*$/, '');
  const visual = (tr.settings && tr.settings.visual) || 'fx';
  return [`$: (${code.includes('\n') ? '\n  ' + code.split('\n').join('\n  ') + '\n' : code})`, `  ${rack}.mask(${gate}).velocity(${gate}).orbit(${orbit}).analyze("${visual}")`];
}
