// Command line for v2 songs (docs/SONG-FORMAT.md).
//   node tools/song.mjs validate <file.json|dir …>   errors and warnings with JSON paths; exit 1 on errors
//   node tools/song.mjs compile <file.json> [--at N]  print the Strudel code (live build: the code at bar N, from 0)
//   node tools/song.mjs steps <file.json>            live build: each step with its bar and comment
//   node tools/song.mjs list                         songs in songs/ (id, title, file)
// Run with `node --no-warnings` to hide Node's experimental localStorage warning.
import fs from 'node:fs';
import path from 'node:path';
import { songFiles } from './songs-dir.mjs';
import { validateSong } from '../src/song/validate.js';
import { compileSong } from '../src/song/compile.js';
import { hasBuild, buildSteps, stateAt, annotate, sayText, voiceCode, BUILD_ACTIONS } from '../src/song/build.js';

const [cmd, ...args] = process.argv.slice(2);
const read = f => { try { return JSON.parse(fs.readFileSync(f, 'utf8')); } catch (e) { console.error(`${f}: ${e.message}`); process.exit(1); } };

if (cmd === 'validate' && args.length) {
  let bad = 0;
  const files = args.flatMap(a => fs.statSync(a).isDirectory() ? songFiles(a) : [a]);
  for (const f of files) {
    const { errors, warnings } = validateSong(read(f));
    let compiled = '';
    if (!errors.length) try { compileSong(read(f)); } catch (e) { errors.push({ path: '', msg: `does not compile: ${e.message}` }); }
    for (const e of errors) console.log(`${f}: error   ${e.path || '(song)'}: ${e.msg}`);
    for (const w of warnings) console.log(`${f}: warning ${w.path || '(song)'}: ${w.msg}`);
    if (!errors.length && !warnings.length) console.log(`${f}: ok${compiled}`);
    if (errors.length) bad++;
  }
  process.exit(bad ? 1 : 0);
} else if (cmd === 'compile' && args[0]) {
  const song = read(args[0]), { errors } = validateSong(song);
  if (errors.length) { for (const e of errors) console.error(`error ${e.path}: ${e.msg}`); process.exit(1); }
  const i = args.indexOf('--at'), at = i > 0 ? Number(args[i + 1]) : null;
  if (at !== null && !Number.isFinite(at)) { console.error('--at needs a bar number'); process.exit(2); }
  // a live build plays its steps: without --at the code is the one at bar 0
  if (hasBuild(song)) {
    // spoken comments generated by tools/voice.mjs, as the app sees them
    const files = Object.fromEntries(['en', 'it'].map(l => [`say_${l}`, fs.existsSync(`public/samples/say_${l}`) ? fs.readdirSync(`public/samples/say_${l}`).filter(f => f.endsWith('.wav')).sort().map(f => `say_${l}/${f}`) : []]));
    const st = stateAt(song, at ?? 0), total = song.sections.reduce((a, x) => a + x.bars, 0);
    process.stdout.write(annotate(compileSong(st.song), song, st.upTo, 'en') + voiceCode(song, st.song, st.upTo, total, 'en', files) + '\n');
  }
  else process.stdout.write(compileSong(song) + '\n');
} else if (cmd === 'steps' && args[0]) {
  const song = read(args[0]);
  if (!hasBuild(song)) { console.log(`${args[0]}: no build steps`); process.exit(0); }
  for (const s of buildSteps(song)) {
    const what = BUILD_ACTIONS.filter(k => s[k] !== undefined).map(k => `${k} ${JSON.stringify(s[k])}`).join(', ');
    console.log(`bar ${String(s.at + 1).padStart(3)}  ${what}${s.say ? `  // ${sayText(s.say, 'en')}` : ''}`);
  }
} else if (cmd === 'list') {
  for (const f of songFiles('songs')) { const s = read(f); console.log(`${s.id}\t${s.title}\t${f}`); }
} else {
  console.error('usage: node tools/song.mjs validate <file|dir …> | compile <file> [--at N] | steps <file> | list');
  process.exit(2);
}
